app = "trnapp"

[build]
  image = ""

[env]
  PORT = "8080"
  DB_PATH = "/data/survey.db"
  RESPONSES_DIR = "/data/responses"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.http_checks]
    interval = 10000
    timeout = 2000
    grace_period = "5s"
    method = "get"
    path = "/health"
    protocol = "http"

[mounts]
  source = "trndata"
  destination = "/data"

[experimental]
  allowed_public_ports = [8080]
  auto_rollback = true
